### ISSUE TITLE
Cannot copy/paste text from Eclipse to Wayland applications

### ISSUE THREAD

**Issue by weberhofer** [eclipse-platform/eclipse.platform.swt#421]
Eclipse should ideally prefer mimetype strings in clipboard and drag and drop targets for both
Wayland and X11, over old-style `STRING` and `UTF8_STRING` format strings. Since the wayland protocols
specify that the types passed must be mimetype strings, this results in failed clipboard operations
with other Wayland clients. Mimetype strings like `text/plain` and `text/plain;charset=utf-8` are
widely accepted both in X11 and Wayland.

This ticket s related to https://gitlab.gnome.org/GNOME/mutter/-/issues/2448

**Comment by robmv** [comment]
This still is a problem even with the latest GTK 3.24.35 that includes the additional translation merged on https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/5072

**Comment by ichbindannmalwegmann** [comment]
I got this from my gnome issue: https://gitlab.gnome.org/GNOME/mutter/-/issues/2536#note_1606119

**Comment by akurtakov** [comment]
Same issue with KDE apps https://bugs.eclipse.org/bugs/show_bug.cgi?id=579653

**Comment by weberhofer** [comment]
IMHO the problem even got worse with Eclipse 2022-12.

**Comment by lalmeras** [comment]
Same here ; Eclipse 2022-12 copy paste does not work. Same with Dbeaver 22.2.5.202211202223 (eclipse-based).

Same applications with `GDK_BACKEND=x11` works fine.

**Comment by lalmeras** [comment]
After some digging : gtk 3.24.35 tries to fix this issue, but fails to do so: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/5072

Another issue that seems to be related with this issue and is merged into gtk 3.24 but not released : https://gitlab.gnome.org/GNOME/gtk/-/issues/5397

On my side, I try the proposed patch and it solves the copy issue (from eclipse/dbeaver to firefox). So gtk 3.24.36 release should improve the situation.

**Comment by ichbindannmalwegmann** [comment]
Now gtk3-3.24.36-1 (https://bugzilla.redhat.com/show_bug.cgi?id=2151603) works.

**Comment by mickaelistria** [comment]
I confirm gtk3-3.23.36-1 fixes the issue here on my Fedora 37!

**Comment by akurtakov** [comment]
Closing as this has been fixed in latest gtk3 and changing swt gtk3 clipboard implementation has to potential to destabilize things and gtk4 port has it working with the new approach already.

**Comment by derkoe** [comment]
I can still reproduce the issue with GTK 3.24.37 (Ubuntu lunar) with Eclipse 2023-03.

This only happens with non-ASCII characters (like umlauts).

The paste does work in text fields (for example in all dialogs) but it does not work in any editor.

**Comment by lemmyg** [comment]
yep, same issue in Kubuntu 23.04 wayland and Eclipse 2022-03.
for example, copying any text from a KDE application to eclipse is impossible.

**Comment by weberhofer** [comment]
This issue has never been resolved.

**Comment by the-snowwhite** [comment]
@weberhofer 
The: copy/paste text from Eclipse to Wayland applications is solved by updating the gtk3 library  to a version equal to or higher than 3.24.36.
I have tested this on kde Neon.
Fedore 38 and Kubuntu 23.10 have this fix built in.
However there is still an issue with copying from KDE applications to eclipse in Wayland session. 
So I have just opened this issue: #851
