### ISSUE TITLE
GLCanvas not working on Wayland

### ISSUE THREAD

**Issue by wolfseifert** [eclipse-platform/eclipse.platform.swt#806]
**Describe the bug**
SWT's GLCanvas is not working on Wayland.
Running code Snippet195, Snippet209 or Snippet341 I get:
Exception in thread "main" org.eclipse.swt.SWTException: Unsupported color depth
Running these snippets on X11 works fine.

**To Reproduce**
$ javac -cp swt-gtk-linux-x86_64-4.29.jar:lwjgl-opengl-3.3.2.jar -d . Snippet195.java
$ java -cp .:swt-gtk-linux-x86_64-4.29.jar:lwjgl-3.3.2.jar:lwjgl-3.3.2-natives-linux.jar:lwjgl-opengl-3.3.2.jar:lwjgl-opengl-3.3.2-natives-linux.jar org.eclipse.swt.snippets.Snippet195
Exception in thread "main" org.eclipse.swt.SWTException: Unsupported color depth
        at org.eclipse.swt.SWT.error(SWT.java:4918)
        at org.eclipse.swt.SWT.error(SWT.java:4833)
        at org.eclipse.swt.SWT.error(SWT.java:4804)
        at org.eclipse.swt.opengl.GLCanvas.<init>(GLCanvas.java:118)
        at org.eclipse.swt.snippets.Snippet195.main(Snippet195.java:67)

$ javac -cp swt-gtk-linux-x86_64-4.29.jar:jogl-all-v2.4.0.jar -d . Snippet209.java
$ java -cp .:swt-gtk-linux-x86_64-4.29.jar:jogl-all-v2.4.0.jar:jogl-all-v2.4.0-natives-linux-amd64.jar:gluegen-rt-v2.4.0.jar org.eclipse.swt.snippets.Snippet209
Exception in thread "main" org.eclipse.swt.SWTException: Unsupported color depth
        at org.eclipse.swt.SWT.error(SWT.java:4918)
        at org.eclipse.swt.SWT.error(SWT.java:4833)
        at org.eclipse.swt.SWT.error(SWT.java:4804)
        at org.eclipse.swt.opengl.GLCanvas.<init>(GLCanvas.java:118)
        at org.eclipse.swt.snippets.Snippet209.main(Snippet209.java:69)

$ javac -cp swt-gtk-linux-x86_64-4.29.jar:lwjgl-opengl-3.3.2.jar -d . Snippet341.java
$ java -cp .:swt-gtk-linux-x86_64-4.29.jar:lwjgl-3.3.2.jar:lwjgl-3.3.2-natives-linux.jar:lwjgl-opengl-3.3.2.jar:lwjgl-opengl-3.3.2-natives-linux.jar org.eclipse.swt.snippets.Snippet341
Exception in thread "main" org.eclipse.swt.SWTException: Unsupported color depth
        at org.eclipse.swt.SWT.error(SWT.java:4918)
        at org.eclipse.swt.SWT.error(SWT.java:4833)
        at org.eclipse.swt.SWT.error(SWT.java:4804)
        at org.eclipse.swt.opengl.GLCanvas.<init>(GLCanvas.java:118)
        at org.eclipse.swt.snippets.Snippet341.main(Snippet341.java:70)

**Expected behavior**
These snippets should run without issues (like in X11 environment).

**Environment:**
Linux with KDE or GNOME, JDK 21 or earlier.

**Workaround (or) Additional context**
Use X11.

**Comment by akurtakov** [comment]
This is known issue as the GLCanvas is GLX based (aka direct X11 dependencies). It would be best (and probably simpler implementation) to redo GLCanvas on top of https://docs.gtk.org/gtk3/class.GLArea.html to make it work under all Gtk backends. Unfortunately, we are quite low on resources and no one is looking at this work AFAIK. If you consider to try it yourself I'll be more than happy to help.

**Comment by akurtakov** [comment]
@jonahgraham Could there be interest by the IDE WG to fund this one?

**Comment by laeubi** [comment]
It might be a good opportunity to use the new [FFM Api](https://openjdk.org/jeps/442) for that, I'm already using it and it works really great, since this is available from Java 17 and Tycho support building Multi-Release-Jars now this would make this much easier than writing native code here.

**Comment by wolfseifert** [comment]
Setting `GDK_BACKEND=x11` in the environment makes it possible to run SWT's GLCanvas on Wayland (see #639).

**Comment by shartrec** [comment]
I have just tested using my application and this appears fixed in latest Eclipse 2025-12. 

I'm not sure what may have been done, but there is a general project to get Wayland support in SWT. https://github.com/eclipse-platform/eclipse.platform.swt/issues/639

**Comment by wolfseifert** [comment]
Still not working for me!

Tested with SWT 4.39 RC1 (19 Feb 2026), LWJGL 3.3.6, JOGL 2.6.0 and Java 25.

Setting `GDK_BACKEND=x11` in the environment makes it possible to run on XWayland.
